### ISSUE TITLE
Update to latest JOSM

### ISSUE THREAD

**Issue by don-vip** [risicle/josm-markseen#1]
We have removed a lot of deprecated API as advertised on the mailing list, see https://josm.openstreetmap.de/ticket/15310

As a result this plugin is no longer compatible, can you please update it?

Thanks.

**Comment by risicle** [comment]
Ok, I was holding off as long as possible to try and retain compatibility back to 12545, but will push out the updates now.

**Comment by risicle** [comment]
Done in release v7: https://github.com/risicle/josm-markseen/releases/tag/v7
