### ISSUE TITLE
markseen does not work with JOSM 14253+

### ISSUE THREAD

**Issue by don-vip** [risicle/josm-markseen#2]
`Main` was deprecated. It's gone in [JOSM 14253](https://josm.openstreetmap.de/changeset/14253/josm/).

`Main.pref` must be almost always replaced by `Config.getPref()` (introduced in [JOSM 12847](https://josm.openstreetmap.de/changeset/12847/josm)).
Few advanced methods can only be called from `Preferences.main()` (introduced in [JOSM 14149](https://josm.openstreetmap.de/changeset/14149/josm)).

Plugin must be [updated](https://josm.openstreetmap.de/jenkins/job/JOSM-Integration/jdk=JDK8/2081/warnings3Result/type.247375560/) and a new version released.

**Comment by risicle** [comment]
Aww, I was holding off as long as possible to allow me to keep a single compatible version, but I'll use the oldversion system.

**Comment by risicle** [comment]
Meh - turns out my `mainversion` was post-12847 anyway, so I didn't need to change that. Fixed in v9. Thanks for the notice.
