### ISSUE TITLE
Bad Plugin-Url

### ISSUE THREAD

**Issue by don-vip** [risicle/josm-markseen#3]
See https://josm.openstreetmap.de/jenkins/job/JOSM-Integration/lastCompletedBuild/jdk=JDK8/testReport/org.openstreetmap.josm.plugins/PluginHandlerTestIT/testValidityOfAvailablePlugins/

```
 Error Details
[markseen=[13053_Plugin-Url]]

```

**Comment by risicle** [comment]
Thanks - should be fixed now with v11
