### ISSUE TITLE
weird behaviour of Markseen

### ISSUE THREAD

**Issue by FransS1945** [risicle/josm-markseen#4]
JOSM ver 15155 (and before) There is a weird behaviour of Markseen. It shows rectangulars with red crosses flickering all over the time. 
![afbeelding](https://user-images.githubusercontent.com/31804031/59599273-71fcda00-90fe-11e9-943c-01bfc16dcdca.png)

**Comment by risicle** [comment]
Hmm. That's not really got anything to do with markseen from what I can tell - it's just the slippy map not being able to load the background tiles. If you open the "mini map" window and switch it to the same tile source, does it do the same? The markseen viewer is just a pimped up version of the mini map window.
